spring:
  application:
    name: "ticket"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5434/ticketdb
    username: postgres
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

server:
  port: 8090

