spring:
  application:
    name: "ticket"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5434/ticketdb
    username: postgres
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  cloud:
    function:
      definition: createdTicketsForTour
    stream:
      bindings:
        createdTicketsForTour-in-0:
          destination: tour-sent-events
      kafka:
        binder:
          brokers:
            - localhost:9092

server:
  port: 8090
logging:
  level:
    com:
      musicband:
        ticket: DEBUG

