#spring.application.name=tour

spring:
  application:
    name: "tour"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5433/tourdb
    username: postgres
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  cloud:
    stream:
      bindings:
        tourCreatedEvents-out-0:
          destination: tour-created-events
          group: "tour-created-events-tour"
        tourUpdatedEvents-out-0:
          destination: tour-updated-events
          group: "tour-updated-events-tour"
        tourDeletedEvents-out-0:
          destination: tour-deleted-events
          group: "tour-deleted-events-tour"
      kafka:
        binder:
          brokers:
            - localhost:9092

server:
  port: 8080
logging:
  level:
    com:
      musicband:
        tour: DEBUG
