spring:
  application:
    name: "notification"
  config:
    import: "optional:configserver:http://localhost:8071/"
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  cloud:
    function:
      definition: tourUpdatedMessage;tourDeletedMessage;ticketUpdatedMessage;orderStatusMessage
    stream:
      bindings:
        tourUpdatedMessage-in-0:
          destination: notification-tour-updated-events
          group: "notification-tour-updated-events-notification"
        tourDeletedMessage-in-0:
          destination: notification-tour-deleted-events
          group: "notification-tour-deleted-events-notification"
        ticketUpdatedMessage-in-0:
          destination: notification-new-tickets-events
          group: "notification-new-tickets-events-notification"
        orderStatusMessage-in-0:
          destination: notification-order-status-payment
          group: "notification-order-status-payment-notification"
      kafka:
        binder:
          brokers:
            - localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${email_smtp}"
    password: "${smtp_password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8073
logging:
  level:
    com:
      musicband:
        notification: DEBUG