spring:
  application:
    name: "payment"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:postgresql://localhost:5435/paymentdb
    username: postgres
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  cloud:
    function:
      definition: orderTicketPayment;orderMerchPayment
    stream:
      bindings:
        orderTicketPayment-in-0:
          destination: payment-order-ticket-events
          group: "payment-order-ticket-events-payment"
        orderTicketStatusPayment-out-0:
          destination: order-status-ticket-payment
          group: "order-status-ticket-payment-payment"
        orderMerchPayment-in-0:
          destination: payment-order-merch-events
          group: "payment-order-merch-events-payment"
        orderMerchStatusPayment-out-0:
          destination: order-status-merch-payment
          group: "order-status-merch-payment-payment"
      kafka:
        binder:
          brokers:
            - localhost:9092

server:
  port: 9000
logging:
  level:
    com:
      musicband:
        tour: DEBUG
